name: Custom CI

on: 
    push:
        branches:
            - CIv2

jobs:
    
    main:
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v3
            - uses: GH-Action/Custom@CIv2
